#!/bin/bash -eu
set -o pipefail

(cd $(dirname $0)
	echo "=== BEGIN: JavaScript ==="
	(cd js/example
		npm install
		npm test
	)
	echo "=== END: JavaScript ==="

	echo "=== BEGIN: TypeScript ==="
	(cd ts/example
		npm install
		npm test
	)
	echo "=== END: TypeScript ==="
)
